#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
alias lg="git lg"
alias sub="/home/luke/Downloads/Sublime\ Text\ 2/sublime_text"
alias s="git status"
alias f="git diff"
alias fs="git diff --staged"
alias a="git add"
alias mtag="maiden tagRevision"
alias l="ls -la"
alias ltag="git tag |sort -V| tail -n 10"
unsetopt correct_all
